### ISSUE TITLE
Warning Action Preference

### ISSUE THREAD

**Issue by istairbn** [xebialabs-community/xlr-powershell-plugin#3]
I have a couple of PowerShell tasks which throw out large amounts of Warnings. 

Regardless of what I do in the script to catch or hide them, the output contains the full list of warnings. This means that I have to scrape the output before using it in future tasks.

Would it be possible to set the WarningPreference for a PowerShell action? We currently set errorpreference as stop, but we don't set the ErrorPreference at all. 
It would be nice if the default was continue (current) but you could also switch it to silentlycontinue (remove verbose output) or stop (ultra paranoia level)

**Comment by jdewinne** [comment]
Added both options in [v1.1.0](https://github.com/xebialabs-community/xlr-powershell-plugin/releases/tag/v1.1.0)
